version: "3.9"

services:
  # PostgreSQL-Datenbank-Container
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cooking_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cooking_network

  # Frontend: Streamlit App
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/cooking_db"
    networks:
      - cooking_network

  # Vorrat-Service
  vorrat_service:
    build:
      context: .
      dockerfile: services/vorrat_service/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/cooking_db"
    networks:
      - cooking_network

  # Rezepte-Service
  rezept_service:
    build:
      context: .
      dockerfile: services/rezept_service/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/cooking_db"
    networks:
      - cooking_network

  # Vorschlag-Service
  vorschlag_service:
    build:
      context: .
      dockerfile: services/vorschlag_service/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/cooking_db"
    networks:
      - cooking_network

  # Einkaufsliste-Service
  einkaufsliste_service:
    build:
      context: .
      dockerfile: services/einkaufsliste_service/Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/cooking_db"
    networks:
      - cooking_network

  # Rezept-Import-Service
  rezept_import_service:
    build:
      context: .
      dockerfile: services/rezept-import_service/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/cooking_db"
      OPENAI_API_KEY: "${openai_api_key}"
    networks:
      - cooking_network

volumes:
  pgdata:

networks:
  cooking_network:
    driver: bridge
